services:
  - type: web
    name: object-detection-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn object_detection.wsgi:application
    envVars:
      - key: DEBUG
        value: true
